[tool.poetry]
name = "pkg-a"
version = "0.1.0"
description = ""
authors = ["Jonathan Rayner <jonathan.j.rayner@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11 <3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
